version: '3.8'

services:
  backend:
    build: ./backend
    container_name: immigration-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
    networks:
      - immigration-network

  frontend:
    build: ./frontend
    container_name: immigration-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - immigration-network

networks:
  immigration-network:
    driver: bridge 