# Generated by Django 5.2 on 2025-06-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('nationality', models.CharField(max_length=100, verbose_name='Quốc tịch')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Số hộ chiếu')),
                ('passport_expiry_date', models.DateField(verbose_name='Ngày hết hạn hộ chiếu')),
                ('entry_type', models.CharField(choices=[('ENTRY', 'Nhập cảnh'), ('EXIT', 'Xuất cảnh')], max_length=5, verbose_name='Loại cửa khẩu')),
                ('purpose', models.CharField(choices=[('TOURISM', 'Du lịch'), ('BUSINESS', 'Công việc'), ('STUDY', 'Học tập'), ('VISIT', 'Thăm thân'), ('DIPLOMATIC', 'Ngoại giao'), ('OTHER', 'Khác')], max_length=10, verbose_name='Mục đích')),
                ('purpose_detail', models.TextField(blank=True, null=True, verbose_name='Chi tiết mục đích')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Số hiệu chuyến bay')),
                ('airline', models.CharField(max_length=100, verbose_name='Hãng hàng không')),
                ('date_of_entry_exit', models.DateTimeField(verbose_name='Thời gian xuất/nhập cảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo bản ghi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('status', models.CharField(choices=[('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('PENDING', 'Đang xử lý')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('visa_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số thị thực')),
                ('address_in_country', models.TextField(blank=True, null=True, verbose_name='Địa chỉ lưu trú')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại liên hệ')),
            ],
            options={
                'verbose_name': 'Bản ghi xuất nhập cảnh',
                'verbose_name_plural': 'Bản ghi xuất nhập cảnh',
                'ordering': ['-date_of_entry_exit'],
            },
        ),
    ]
