# Generated by Django 5.2 on 2025-06-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigrationrecord',
            name='date_of_entry_exit',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian xuất/nhập cảnh'),
        ),
        migrations.AlterField(
            model_name='immigrationrecord',
            name='gender',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1, verbose_name='Giới tính'),
        ),
    ]
